# Generated by Django 2.1.3 on 2018-11-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_use', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_decade',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('cate_log_name', models.CharField(max_length=255)),
                ('cate_log_id', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_use', models.IntegerField()),
                ('loc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('on_decade', models.CharField(blank=True, max_length=255, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
                ('is_vip', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_film',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_use', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_level',
            },
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_use', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_loc',
            },
        ),
        migrations.CreateModel(
            name='Raty',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('en_time', models.CharField(blank=True, max_length=255, null=True)),
                ('film_id', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_raty',
            },
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('episodes', models.IntegerField()),
                ('is_use', models.IntegerField()),
                ('link', models.TextField(blank=True, null=True)),
                ('link_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
                ('film_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_res',
            },
        ),
        migrations.CreateModel(
            name='ResCopy1',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('episodes', models.IntegerField()),
                ('is_use', models.IntegerField()),
                ('link', models.TextField(blank=True, null=True)),
                ('link_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
                ('film_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_res_copy1',
            },
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_use', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_subclass',
            },
        ),
        migrations.CreateModel(
            name='TType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_use', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('subclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.SubClass')),
            ],
            options={
                'db_table': 't_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('is_vip', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('passwd', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manager', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_use', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_vipcode',
            },
        ),
        migrations.CreateModel(
            name='VipCodeCopy1',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_use', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_vipcode_copy1',
            },
        ),
    ]
