# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-23 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cate_log_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CateLog'),
        ),
    ]
